In [23]:
from sklearn.datasets import load_digits, load_breast_cancer
from sklearn.cross_validation import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

import numpy as np

In [2]:
digits = load_digits()
breast_cancer = load_breast_cancer()

In [21]:
digits.data[:5]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  

In [19]:
digits.target[:5]

array([0, 1, 2, 3, 4])

In [22]:
breast_cancer.data[:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [20]:
breast_cancer.target[:5]

array([0, 0, 0, 0, 0])

In [48]:
bern_estimator = BernoulliNB()
multinom_estimator = MultinomialNB()
gauss_estimator = GaussianNB()

In [49]:
score_bern = cross_val_score(estimator=bern_estimator, X=digits.data, y=digits.target)
score_multi = cross_val_score(estimator=multinom_estimator, X=digits.data, y=digits.target)
score_gauss = cross_val_score(estimator=gauss_estimator, X=digits.data, y=digits.target)

In [51]:
print(score_bern.mean())
print(score_multi.mean())
print(score_gauss.mean())

with open("answer2.txt", "w") as file1:
    file1.write(str(score_multi.mean()))

0.8258236507780582
0.8708771489735053
0.8186003803550138


In [52]:
score_bern = cross_val_score(estimator=bern_estimator, X=breast_cancer.data, y=breast_cancer.target)
score_multi = cross_val_score(estimator=multinom_estimator, X=breast_cancer.data, y=breast_cancer.target)
score_gauss = cross_val_score(estimator=gauss_estimator, X=breast_cancer.data, y=breast_cancer.target)

In [53]:
print(score_bern.mean())
print(score_multi.mean())
print(score_gauss.mean())

with open("answer1.txt", "w") as file1:
    file1.write(str(score_gauss.mean()))

0.6274204028589994
0.8945790401930752
0.9367492806089297


In [54]:
with open("answer3.txt", "w") as file1:
    file1.write("3 4")