In [202]:
####     Example 7.2.2  (Table 3.5)  Rencher. Тести для ков. матриць
## Тесе на діагональність ков. матриці
import numpy as np
path = 'c:/Users/vica/Dropbox/KAU-Stat2/multivariate_analysis/T3_5_PROBE.DAT'
Data_3_5 = np.loadtxt(path, dtype=int)
print(Data_3_5)


[[ 1 51 36 50 35 42]
 [ 2 27 20 26 17 27]
 [ 3 37 22 41 37 30]
 [ 4 42 36 32 34 27]
 [ 5 27 18 33 14 29]
 [ 6 43 32 43 35 40]
 [ 7 41 22 36 25 38]
 [ 8 38 21 31 20 16]
 [ 9 36 23 27 25 28]
 [10 26 31 31 32 36]
 [11 29 20 25 26 25]]


In [203]:
Data_3_5_new = Data_3_5[:,1:]  # видаляємо перший стовбчик, оскільки там нумерація
print(Data_3_5_new)

[[51 36 50 35 42]
 [27 20 26 17 27]
 [37 22 41 37 30]
 [42 36 32 34 27]
 [27 18 33 14 29]
 [43 32 43 35 40]
 [41 22 36 25 38]
 [38 21 31 20 16]
 [36 23 27 25 28]
 [26 31 31 32 36]
 [29 20 25 26 25]]


In [204]:
n = len(Data_3_5_new)  # кількість випробувань
n

11

In [205]:
xbar = np.mean(Data_3_5_new,axis=0) # порахуємо середнє
np_xbar = np.round((xbar), 2)       # округимо до 2го знаку
np_xbar

array([36.09, 25.55, 34.09, 27.27, 30.73])

In [206]:
# cov
S = np.cov(Data_3_5_new.T)
S

array([[65.09090909, 33.64545455, 47.59090909, 36.77272727, 25.42727273],
       [33.64545455, 46.07272727, 28.94545455, 40.33636364, 28.36363636],
       [47.59090909, 28.94545455, 60.69090909, 37.37272727, 41.12727273],
       [36.77272727, 40.33636364, 37.37272727, 62.81818182, 31.68181818],
       [25.42727273, 28.36363636, 41.12727273, 31.68181818, 58.21818182]])

In [207]:
det_S= np.linalg.det(S)   # det(cov)
det_S

27236585.648872674

In [208]:
Tr_S = np.trace(S, offset=0, axis1=0, axis2=1, dtype=None, out=None)   # trace(cov)
Tr_S

292.8909090909091

In [209]:
p = len(S)    #  dim(cov)
p

5

In [210]:
# Обчислимо статистику  U = ((p^p)*det(S))/(TrS)^p
U = (p**p)*det_S/((Tr_S)**p)
U

0.03948873535811227

In [45]:
til_U = -(n-1-(2*p**2 +p+2)/(6*p)) * np.log(U)     # Обчислимо статистику  til_U 
til_U

26.177092611288405

In [82]:
# знайдемо квантіль розподілу хі квадрат з p(p+1)/2 = 15  ступенями свободи
    
from scipy.stats import chi2  #
chi2.ppf(0.95, 14, loc=0, scale=1)  # Отримали:  26.17 > 23.68
                                    # тому відхиляємо нульову гіпотезу про те, що Sigma= sigma I

23.684791304840576

In [30]:
# "Build in" function 

import pandas as pd
import pingouin as pg
# pg.sphericity(data) Mauchly test (sphericity, Sigma = sigma^2 I
data = pd.DataFrame(Data_3_5_new)
pg.sphericity(data)

NameError: name 'Data_3_5_new' is not defined

In [ ]:
# Увага! pg.sphericity(data) обчислює не U- статистику і значення  квантілю chi2!!! 
# Це перевірка іншої сферичності! 
# https://github.com/raphaelvallat/pingouin/blob/dcfdc82bbc7f1ba5991b80717a5ca156617443e8/pingouin/distribution.py
# А також Rencher, розділ   7.2.2

In [31]:
#  Тест на рівність коваріацій у двох вибірках  
#  Example 7.3.2  (Table 5.1)  Rencher\
#  https://pingouin-stats.org/generated/pingouin.box_m.html
path = 'c:/Users/vica/Dropbox/KAU-Stat2/multivariate_analysis/T5_1_PSYCH.DAT'
Data_5_1 = np.loadtxt(path, dtype=int)
Data_5_1M = Data_5_1[0:32,1:] 
Data_5_1F = Data_5_1[32:,1:]
np.shape(Data_5_1M)
data = pd.DataFrame(Data_5_1[:,1:], columns=['A', 'B', 'C','D'])
data['group'] = [1] * 32 + [2] * 32 
data.head()
pg.box_m(data, dvs=['A', 'B', 'C','D'], group='group')  # 10 = 0.5* (k-1)*p(p+1), k=2, p=4

Chi2    df      pval  equal_cov
box  13.550751  10.0  0.194487       True

In [198]:
# Руками: 
d1 = len(Data_5_1M)  # 32
d2 = len(Data_5_1F)  # 32
Spl = ((d1-1)*np.cov(Data_5_1M.T)+ (d2-1)*np.cov(Data_5_1F.T))/(d1+d2-2)
Spl

array([[ 7.16431452,  6.04737903,  5.69304435,  4.70060484],
       [ 6.04737903, 15.89415323,  8.49243952,  5.85584677],
       [ 5.69304435,  8.49243952, 29.35635081, 13.98084677],
       [ 4.70060484,  5.85584677, 13.98084677, 22.32056452]])

In [220]:
Det1 = np.linalg.det(np.cov(Data_5_1M.T))

In [228]:
Det1 = np.linalg.det(np.cov(Data_5_1M.T))
Det2 = np.linalg.det(np.cov(Data_5_1F.T))
Det = np.linalg.det(Spl)

M = ((Det1)**(d1/2))*((Det2)**(d2/2))/((Det)**(d1/2+d2/2)) # (7.21)
M

0.0005447693950026875

In [232]:
d=32
k = 2
p =  4
C1=(k+1)*(2*p**2+3*p-1)/(6*k*d * (p+1))
C1
u= -2*(1-C1)*np.log(M) #(7.23) Rencher
u                      # 

14.02044795257655

In [233]:
# 0.5* (k-1)*p*(p+1)=10
chi2.ppf(0.95, 10, loc=0, scale=1)   # 14.02< 18.3  Прийняти  H_0

18.307038053275146

In [3]:
# Example 7.4.1
# Таблиця 3.4  Wilks Lambda 
# import numpy as np
path = 'c:/Users/vica/Dropbox/KAU-Stat2/multivariate_analysis/T3_4_DIABETES.DAT'
Data_3_4 = np.loadtxt(path, dtype=float)
print(Data_3_4)


[[  1.     0.81  80.   356.   124.    55.  ]
 [  2.     0.95  97.   289.   117.    76.  ]
 [  3.     0.94 105.   319.   143.   105.  ]
 [  4.     1.04  90.   356.   199.   108.  ]
 [  5.     1.    90.   323.   240.   143.  ]
 [  6.     0.76  86.   381.   157.   165.  ]
 [  7.     0.91 100.   350.   221.   119.  ]
 [  8.     1.1   85.   301.   186.   105.  ]
 [  9.     0.99  97.   379.   142.    98.  ]
 [ 10.     0.78  97.   296.   131.    94.  ]
 [ 11.     0.9   91.   353.   221.    53.  ]
 [ 12.     0.73  87.   306.   178.    66.  ]
 [ 13.     0.96  78.   290.   136.   142.  ]
 [ 14.     0.84  90.   371.   200.    93.  ]
 [ 15.     0.74  86.   312.   208.    68.  ]
 [ 16.     0.98  80.   393.   202.   102.  ]
 [ 17.     1.1   90.   364.   152.    76.  ]
 [ 18.     0.85  99.   359.   185.    37.  ]
 [ 19.     0.83  85.   296.   116.    60.  ]
 [ 20.     0.93  90.   345.   123.    50.  ]
 [ 21.     0.95  90.   378.   136.    47.  ]
 [ 22.     0.74  88.   304.   134.    50.  ]
 [ 23.    

In [17]:
Data_3_4_new = Data_3_4[:,1:] 
S = np.cov(Data_3_4_new.T)
S

array([[ 1.61818357e-02,  2.16028986e-01,  7.87169082e-01,
        -2.13845411e-01,  2.18907246e+00],
       [ 2.16028986e-01,  7.05589372e+01,  2.62289855e+01,
        -2.39560386e+01, -2.08415459e+01],
       [ 7.87169082e-01,  2.62289855e+01,  1.10641353e+03,
         3.96732367e+02,  1.08383575e+02],
       [-2.13845411e-01, -2.39560386e+01,  3.96732367e+02,
         2.38188261e+03,  1.14263768e+03],
       [ 2.18907246e+00, -2.08415459e+01,  1.08383575e+02,
         1.14263768e+03,  2.13639614e+03]])

In [22]:
Syy = S[0:2,0:2]
Syy

array([[1.61818357e-02, 2.16028986e-01],
       [2.16028986e-01, 7.05589372e+01]])

In [19]:
Sxx = S[2:,2:]
Sxx

array([[1106.41352657,  396.73236715,  108.38357488],
       [ 396.73236715, 2381.8826087 , 1142.63768116],
       [ 108.38357488, 1142.63768116, 2136.39613527]])

In [23]:
Lambda =  np.linalg.det(S)/ (np.linalg.det(Sxx)*np.linalg.det(Syy))
Lambda

0.7240096269007144