In [25]:
# ANOVA + MANOVA
import pandas as pd
import numpy as np
import csv
# Просто задача, не з Ренчер
# Зчитаємо файл PlantGrowth.csv
# Треба на Github обрати raw


url = (r'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/PlantGrowth.csv')
Plant = pd.read_csv(url)

print(Plant) 


    Unnamed: 0  weight group
0            1    4.17  ctrl
1            2    5.58  ctrl
2            3    5.18  ctrl
3            4    6.11  ctrl
4            5    4.50  ctrl
5            6    4.61  ctrl
6            7    5.17  ctrl
7            8    4.53  ctrl
8            9    5.33  ctrl
9           10    5.14  ctrl
10          11    4.81  trt1
11          12    4.17  trt1
12          13    4.41  trt1
13          14    3.59  trt1
14          15    5.87  trt1
15          16    3.83  trt1
16          17    6.03  trt1
17          18    4.89  trt1
18          19    4.32  trt1
19          20    4.69  trt1
20          21    6.31  trt2
21          22    5.12  trt2
22          23    5.54  trt2
23          24    5.50  trt2
24          25    5.37  trt2
25          26    5.29  trt2
26          27    4.92  trt2
27          28    6.15  trt2
28          29    5.80  trt2
29          30    5.26  trt2


In [26]:
# https://www.marsja.se/four-ways-to-conduct-one-way-anovas-using-python/

ctrl = Plant['weight'][Plant.group == 'ctrl']
grps = pd.unique(Plant.group.values)
d_data = {grp:Plant['weight'][Plant.group == grp] for grp in grps}

k = len(pd.unique(Plant.group))  # кількість груп   3
N = len(Plant.values)  # k помножити на  n
n = Plant.groupby('group').size()[0] # кількість даних в групі  10

In [27]:
import statsmodels.api as sm
from statsmodels.formula.api import ols  # ols = ordinary least squares

mod = ols('weight ~ group', data=Plant).fit()   # будуємо модель лінійної регресії
aov_table =  sm.stats.anova_lm(mod, type = 2)
print(aov_table)
# print(mod.summary())

            df    sum_sq   mean_sq         F   PR(>F)
group      2.0   3.76634  1.883170  4.846088  0.01591
Residual  27.0  10.49209  0.388596       NaN      NaN


In [4]:
SSbetween = (sum(Plant.groupby('group').sum()['weight']**2)/n) \
    - (Plant['weight'].sum()**2)/N
SSbetween  #SSH

3.766340000000014

In [5]:
sum_y_squared = sum([value**2 for value in Plant['weight'].values])

SSwithin = sum_y_squared - sum(Plant.groupby('group').sum()['weight']**2)/n
SSwithin  #SSE

10.492090000000076

In [6]:
SStotal = sum_y_squared - (Plant['weight'].sum()**2)/N
SStotal  #SST


14.25843000000009

In [7]:
DFbetween = k - 1
DFwithin = N - k
DFtotal = N - 1
MSwithin = SSwithin/DFwithin
MSbetween = SSbetween/DFbetween
F = MSbetween/MSwithin
F

4.846087862380118

In [28]:
# MANOVA Приклад 6.1.7 з Rencher
path = 'c:/Users/vica/Dropbox/KAU-Stat2/multivariate_analysis/T6_2_ROOT.DAT'
Data_6_2 = np.loadtxt(path, dtype=float)
print(Data_6_2)

[[1.    1.11  2.569 3.58  0.76 ]
 [1.    1.19  2.928 3.75  0.821]
 [1.    1.09  2.865 3.93  0.928]
 [1.    1.25  3.844 3.94  1.009]
 [1.    1.11  3.027 3.6   0.766]
 [1.    1.08  2.336 3.51  0.726]
 [1.    1.11  3.211 3.98  1.209]
 [1.    1.16  3.037 3.62  0.75 ]
 [2.    1.05  2.074 4.09  1.036]
 [2.    1.17  2.885 4.06  1.094]
 [2.    1.11  3.378 4.87  1.635]
 [2.    1.25  3.906 4.98  1.517]
 [2.    1.17  2.782 4.38  1.197]
 [2.    1.15  3.018 4.65  1.244]
 [2.    1.17  3.383 4.69  1.495]
 [2.    1.19  3.447 4.4   1.026]
 [3.    1.07  2.505 3.76  0.912]
 [3.    0.99  2.315 4.44  1.398]
 [3.    1.06  2.667 4.38  1.197]
 [3.    1.02  2.39  4.67  1.613]
 [3.    1.15  3.021 4.48  1.476]
 [3.    1.2   3.085 4.78  1.571]
 [3.    1.2   3.308 4.57  1.506]
 [3.    1.17  3.231 4.56  1.458]
 [4.    1.22  2.838 3.89  0.944]
 [4.    1.03  2.351 4.05  1.241]
 [4.    1.14  3.001 4.05  1.023]
 [4.    1.01  2.439 3.92  1.067]
 [4.    0.99  2.199 3.27  0.693]
 [4.    1.11  3.318 3.95  1.085]
 [4.    1.

In [9]:
data = pd.DataFrame(Data_6_2[:,1:], columns=['A', 'B', 'C','D'])
data['group'] = [1] * 8 + [2] * 8+ [3] * 8 + [4] * 8+ [5] * 8 +  [6] * 8
data.head()

A      B     C      D  group
0  1.11  2.569  3.58  0.760      1
1  1.19  2.928  3.75  0.821      1
2  1.09  2.865  3.93  0.928      1
3  1.25  3.844  3.94  1.009      1
4  1.11  3.027  3.60  0.766      1

In [30]:
# інші можливості згрупувати: 
df= pd.DataFrame(Data_6_2[:,1:], columns=['A', 'B', 'C','D'])
df['group'] = Data_6_2[:,0]


In [34]:
# або так, більш компактно: 
df['group'] = [0+ int(x) for x in df['group']]


In [12]:
# тепер завантажимо функцію MANOVA та виконаємо аналіз
from statsmodels.multivariate.manova import MANOVA
fit = MANOVA.from_formula('A+B+C+D ~ group', data=df)
print(fit.mv_test())

                  Multivariate linear model
                                                              
--------------------------------------------------------------
       Intercept         Value  Num DF  Den DF F Value  Pr > F
--------------------------------------------------------------
          Wilks' lambda  0.0112 4.0000 43.0000 950.7953 0.0000
         Pillai's trace  0.9888 4.0000 43.0000 950.7953 0.0000
 Hotelling-Lawley trace 88.4461 4.0000 43.0000 950.7953 0.0000
    Roy's greatest root 88.4461 4.0000 43.0000 950.7953 0.0000
--------------------------------------------------------------
                                                              
--------------------------------------------------------------
           group          Value  Num DF  Den DF F Value Pr > F
--------------------------------------------------------------
            Wilks' lambda 0.7642 4.0000 43.0000  3.3162 0.0187
           Pillai's trace 0.2358 4.0000 43.0000  3.3162 0.0187
   Hotellin

In [13]:
# тут можна прочитати більще https://towardsdatascience.com/manova-97e675a96158   Пояснення + порівняння з R 
# А тут-- подивитися код
# https://www.statsmodels.org/dev/_modules/statsmodels/multivariate/multivariate_ols.html#MultivariateTestResults

In [14]:
# Обчислення матриці  E 
# візьмемо дані без першого рядка 
df = Data_6_2
df_col = df[:,1:]
# Порахуємо суму  sum_{i=1}^k \sum_{j=1}^n y_{ij}y_{ij}'   n=8, k=6
# reshape робимо для того, щоб в результаті отрамати матриці розміру (4,4)
# інакше сприймає вектори як рядки і просто рахує скалярний добуток
A= np.zeros(shape=(4,4))
for i in range(48): 
    A+=(np.array(df_col[i,:]).reshape(4,1))@(np.array(df_col[i,:]).reshape(1,4))
print(A)   


[[ 58.7599   148.2601   217.2267    57.7488  ]
 [148.2601   381.683715 547.9786   147.163597]
 [217.2267   547.9786   812.2905   218.73647 ]
 [ 57.7488   147.163597 218.73647   60.514288]]


In [15]:
# рахуємо суми всередині групи \sum_{i=1}^k y_{i \dot} y_{i \dot}'/n 
g=np.zeros(shape=(6,4))
for i in range(6):
    for j in range(8):
         g[i,:]+= df_col[i*8+j,:]
print(g)

[[ 9.1   23.817 29.91   6.969]
 [ 9.26  24.873 36.12  10.244]
 [ 8.86  22.522 35.64  11.131]
 [ 8.78  23.038 31.25   8.312]
 [ 8.64  20.458 34.5    9.448]
 [ 8.29  17.717 28.77   5.88 ]]


In [16]:
# рахуємо другу суму
B= np.zeros(shape=(4,4))
for i in range(6): 
    B+=(np.array(g[i,:]).reshape(4,1))@(np.array(g[i,:]).reshape(1,4))
print(B/8)  

[[ 58.4399125  146.56353625 216.6726125   57.53166   ]
 [146.56353625 369.54092487 543.6149875  145.05338338]
 [216.6726125  543.6149875  807.9996875  216.25481375]
 [ 57.53166    145.05338338 216.25481375  58.79176325]]


In [17]:
# рахуємо матрицю Е: 
E = A-(B/8)
print(E)

[[ 0.3199875   1.69656375  0.5540875   0.21714   ]
 [ 1.69656375 12.14279013  4.3636125   2.11021363]
 [ 0.5540875   4.3636125   4.2908125   2.48165625]
 [ 0.21714     2.11021363  2.48165625  1.72252475]]


In [18]:
# обчислимо тепер матрицю H. Нам залишилося порахувати   y_{\dot \dot} y_{\dot \dot}'/(kn)
y_2dot= np.sum(g,axis=0)
y_2dot

array([ 52.93 , 132.425, 196.19 ,  51.984])

In [19]:
D = (np.array(y_2dot.reshape(4,1)))@(np.array(y_2dot.reshape(1,4)))
D/48

array([[ 58.36635208, 146.02615104, 216.34034792,  57.32319   ],
       [146.02615104, 365.34126302, 541.25959896, 143.416275  ],
       [216.34034792, 541.25959896, 801.88575208, 212.47377   ],
       [ 57.32319   , 143.416275  , 212.47377   ,  56.298672  ]])

In [20]:
H= B/8- D/48
H

array([[0.07356042, 0.53738521, 0.33226458, 0.20847   ],
       [0.53738521, 4.19966185, 2.35538854, 1.63710838],
       [0.33226458, 2.35538854, 6.11393542, 3.78104375],
       [0.20847   , 1.63710838, 3.78104375, 2.49309125]])

In [21]:
# Wilks Lambda= det(E)/det(E+H)
Lambda =  np.linalg.det(E)/np.linalg.det(E+H)
Lambda

0.15400766733799798

In [22]:
# Pilai statistics
V_s = np.matrix.trace(np.linalg.inv(E+H)@H)
V_s

1.3054724154815531

In [23]:
# F stat
def F(m,s,r,V): 
    F = (2*r+s+1)*V/((2*m+s+1)*(s-V))
    print(F)

p = 4
nu_E = 42  # k(n-1)= 6*7=42
nu_H = 5   # k-1
m = 0.5*(abs(p-nu_H)-1)
r = 0.5*(nu_E-p-1)
s = min(p,nu_H)

print(F(m,s,r,V_s))


4.069718325783936
None


In [24]:
import scipy.stats
scipy.stats.f.ppf(q=1-0.05, dfn=2*m+s+1, dfd=2*r+s+1)  #  Знайшли квантіль розподілу. Відхиляємо гіпотезу

2.437692640311651