In [1]:
# одновимірна модель, лінійна регресія
#  дані з 'Квартету Аскомбе', не з Ренчер
import numpy as np
import math
from sklearn.linear_model import LinearRegression
y = np.array([8.04,6.95,7.58,8.81,8.33,9.96,7.24,4.26,10.84,4.82,5.68])
x1 = [10,8,13,9,11,14,6,4,12,7,5]
x = np.array([10,8,13,9,11,14,6,4,12,7,5]).reshape((-1,1))
w = [math.sqrt(y[i]) for i in range(len(x))]+ np.random.normal(0,1,len(y))
w
print(x)

[[10]
 [ 8]
 [13]
 [ 9]
 [11]
 [14]
 [ 6]
 [ 4]
 [12]
 [ 7]
 [ 5]]


In [2]:
model = LinearRegression().fit(x, y)
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)   # R^2

coefficient of determination: 0.6665424595087748


In [3]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)


intercept: 3.0000909090909094
slope: [0.50009091]


In [4]:
# добавимо ще одну змінну
Z = [[x1[i],w[i]] for i in range(len(x))]
Z

[[10, 2.8071504412856836],
 [8, 3.4177137820668193],
 [13, 1.6357907144600627],
 [9, 2.534765738767161],
 [11, 2.407005599525616],
 [14, 3.7018173078922105],
 [6, 3.6899084232680397],
 [4, 2.5931560110334737],
 [12, 3.5044795599647682],
 [7, 2.7066167211436962],
 [5, 3.5772313641831675]]

In [5]:
model2 = LinearRegression().fit(Z, y)
print('intercept:', model2.intercept_)
print('slope:', model2.coef_)

intercept: -0.6316813278208313
slope: [0.54014428 1.10463572]


In [6]:
# Зробимо повний аналіз моделі. Для цього завантажимо наступні бібліотеки
import statsmodels.api as sm
from statsmodels.api import OLS  # ordinary least squares estimates
Z2 =  [[1,x1[i],w[i]] for i in range(len(x))]
Z2 = np.asarray(Z2)
model2 = LinearRegression().fit(Z2, y)
model3 = sm.OLS(y,Z2)
results = model3.fit() # не дуже точна модель, оскільки мало випробувань
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.793
Model:                            OLS   Adj. R-squared:                  0.742
Method:                 Least Squares   F-statistic:                     15.35
Date:                Tue, 22 Mar 2022   Prob (F-statistic):            0.00183
Time:                        16:53:05   Log-Likelihood:                -14.210
No. Observations:                  11   AIC:                             34.42
Df Residuals:                       8   BIC:                             35.61
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6317      1.890     -0.334      0.7

C:\Users\vica\anaconda3\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [7]:
# окремі обчислення: 
print(results.params) # коефіцієнти

[-0.63168133  0.54014428  1.10463572]


In [8]:
print(results.rsquared) #R2

0.7933060374302633


In [9]:
print(results.bse) # std err

[1.8895717  0.10010539 0.49870158]


In [10]:
print(results.f_pvalue)  # Prob  F-statistic   

0.0018252029629999137


In [11]:
dir(results) # інші параметри- треба дивитися атрібути
# https://www.statsmodels.org/devel/generated/statsmodels.regression.linear_model.OLSResults.html

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_is_nested',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'initia

In [12]:
# https://www.accelebrate.com/blog/interpreting-results-from-linear-regression-is-the-data-appropriate 
# більше пор останній блок резульатів 

In [13]:
# дещо можна було отримати і з model2
print('Intercept: \n', model2.intercept_)  # коефіцієнт при вільному доданку, тобто при 1
print('Coefficients: \n', model2.coef_)    # оцінки коефіцієнтів


Intercept: 
 -0.6316813278208331
Coefficients: 
 [0.         0.54014428 1.10463572]


In [14]:
# оцінка матриці B вручну
B =  np.linalg.inv(Z2.T @ Z2) @ (Z2.T @ y)
B

array([-0.63168133,  0.54014428,  1.10463572])

In [56]:
# Багатовимірна регресія. Приклад  10.4.2 Rencher
import pandas as pd
path = 'c:/Users/vica/Dropbox/KAU-Stat2/multivariate_analysis/T10_1_CHEM.DAT'
df1 = np.loadtxt(path, dtype=float)
data2 = pd.DataFrame(df1[:,1:], columns=['Y1','Y2','Y3','X1', 'X2', 'X3'])
print(data.head())

     Y1    Y2    Y3     X1    X2   X3
0  41.5  45.9  11.2  162.0  23.0  3.0
1  33.8  53.3  11.2  162.0  23.0  8.0
2  27.7  57.5  12.7  162.0  30.0  5.0
3  21.7  58.8  16.0  162.0  30.0  8.0
4  19.9  60.6  16.2  172.0  25.0  5.0


In [57]:
X = df1[:, 4:]  
Y = df1[:,1:4]

In [58]:
from sklearn import linear_model
model_ols =  linear_model.LinearRegression(normalize=True)
results2 = model_ols.fit(X,Y)
print(model_ols.coef_)   # Отримаємо матрицю В  
print(model_ols.intercept_)

[[-1.54596082 -1.42455873 -2.23736565]
 [ 0.40455059  0.29298999  1.03380047]
 [ 0.91392477  0.89947254  1.15348549]]
[ 332.11098334  -26.03526431 -164.0789411 ]


In [1]:
from statsmodels.multivariate.manova import MANOVA
fit1 = MANOVA.from_formula('Y ~ X', data= data2)
print(fit1.mv_test())

NameError: name 'X' is not defined