In [1]:
####################   Приклад 1  ###################
#####Тест про середнє при відомій дисперсії Example 5.2.2

import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist   #  функція cdist обчислює відстань між 2ма векторами

path = 'c:/Users/vica/Dropbox/KAU-Stat2/Table3-1.txt'
Tab_3_1= open(path,'r')               # можна прочитати, але  це буде інший формат     
Tab_3_1.read()

Data_3_1 = np.loadtxt(path, dtype=int)  # конвертуємо в цілі числа,  тип: numpy.ndarray
print(Data_3_1)

[[ 69 153]
 [ 74 175]
 [ 68 155]
 [ 70 135]
 [ 72 172]
 [ 67 150]
 [ 66 115]
 [ 70 137]
 [ 76 200]
 [ 68 130]
 [ 72 140]
 [ 79 265]
 [ 74 185]
 [ 67 112]
 [ 66 140]
 [ 71 150]
 [ 74 165]
 [ 75 185]
 [ 75 210]
 [ 76 220]]


In [2]:
Data_3_1[:,0]  # отримаємо елементи масиву
np.shape(Data_3_1)

(20, 2)

In [47]:
X1=Data_3_1[:,0]; X2=Data_3_1[:,1]
len(X1)                    # довжина масиву  (тут m=20)
xbar=np.mean(Data_3_1,axis=0)   # вектор середніх
xbar.T

array([ 71.45, 164.7 ])

In [4]:
E = [[20,100], [100,1000]]  # матриця Е 
mu0= [70,170]               # вектор mu0
IE = np.linalg.inv(E)       # обернена матриця
IE

array([[ 0.1  , -0.01 ],
       [-0.01 ,  0.002]])

In [5]:
np.dot(IE,xbar-mu0)  # рахуємо скалярний добуток матриці і вектору

array([ 0.198 , -0.0251])

In [6]:
np.dot(xbar-mu0, np.dot(IE,xbar-mu0))   #відстань Махаланобіса в квадраті

0.4201300000000016

In [7]:
# рахуємо 20* відстань Махаланобіса в квадраті
T2_1 = len(X1)*np.dot(xbar-mu0, np.dot(IE,xbar-mu0)) 
T2_1

8.402600000000032

In [8]:
from scipy.spatial import distance        # як порахувати за допомогою  вбудованої функції
(distance.mahalanobis(mu0, xbar, IE))**2  # вбудована функція, відстань Махаланобіса

0.4201300000000016

In [9]:
 # знайдемо квантіль розподілу хі квадрат з 2ма ступенями свободи
    
from scipy.stats import chi2  #
chi2.ppf(0.95, 2, loc=0, scale=1)  # Отримали:  8.4 > 5.99, 
                                   # тому відхиляємо нульову гіпотезу про те, що істине середнє дорівнює mu0.

5.991464547107979

In [10]:
#як порахувати статистику Хотеллінга вбудованою функцією
#!pip install pingouin  
# пакет,  в якому вбудована статистика Хотеллінга
import pingouin as pg

In [11]:
# !pip install hotelling
from hotelling.stats import hotelling_t2
# hotelling.stats.hotelling_dict(x, y=None, bessel=True)  
# bessel: стосується методу, як зобразити щільність розподілу
# https://dionresearch.github.io/hotelling/_modules/hotelling/stats.html#hotelling_diсt

In [65]:
Mu =[[70,170] for i in range(1,21)]  # утворюємо масив із вектору серезніх [70,170]



In [13]:
# порахуємо за допомогою вбудованої функції
pg.multivariate_ttest(Data_3_1,Mu)    # Але це зовсім не T2_1! 

T2          F  df1  df2      pval
hotelling  24.646482  11.998945    2   37  0.000096

In [48]:
hotelling_t2(Data_3_1- Mu, bessel=False, S=None)  # тут справжня ков.матр.

(24.646482117357806,
 11.674649424011593,
 0.0005613570724057936,
 array([[  14.57631579,  128.87894737],
        [ 128.87894737, 1441.27368421]]))

In [16]:
hotelling_t2(Data_3_1- Mu, bessel=False, S=E) # а тут та Е, яка дана

8.402600000000021

In [55]:
## Rencher, Example 5.3.2
## Rencher, Chapter 3, p.56 (стор. 73 у  файлі)
path = 'c:/Users/vica/Dropbox/KAU-Stat2/Table3-3.txt'
Data_3_3 = np.loadtxt(path, dtype=float)  # конвертуємо в дійсні числа,  тип: numpy.ndarray
print(Data_3_3)

[[35.    3.5   2.8 ]
 [35.    4.9   2.7 ]
 [40.   30.    4.38]
 [10.    2.8   3.21]
 [ 6.    2.7   2.73]
 [20.    2.8   2.81]
 [35.    4.6   2.88]
 [35.   10.9   2.9 ]
 [35.    8.    3.28]
 [30.    1.6   3.2 ]]


In [51]:
np.shape(Data_3_3)

(10, 3)

In [56]:
cov = np.cov(Data_3_3.T)  # cov
cov

array([[140.54444444,  49.68      ,   1.94122222],
       [ 49.68      ,  72.24844444,   3.67608889],
       [  1.94122222,   3.67608889,   0.25012111]])

In [58]:
xbar2=np.mean(Data_3_3,axis=0)
mu2=[15.0, 6.0, 2.85]
X=np.subtract(xbar2,mu2)
X

array([13.1  ,  1.18 ,  0.239])

In [59]:
T2_new = 10*(X.T @ np.linalg.inv(cov) @ X)  # 
T2_new

24.558907556462025

In [62]:
Y= np.array([[15.0, 6.0, 2.85]  for i in range(1,11)])
Y

array([[15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85],
       [15.  ,  6.  ,  2.85]])

In [63]:
hotelling_t2(Data_3_3, Y, bessel=False, S=None) 
# T2 stat,  F -stat, p-value, cov matrix
# увага! Тут використовуються масиви, а не вектори! 

(24.558907556461985,
 6.549042015056529,
 0.003831310927774795,
 array([[70.27222222, 24.84      ,  0.97061111],
        [24.84      , 36.12422222,  1.83804444],
        [ 0.97061111,  1.83804444,  0.12506056]]))

In [ ]:
# -*- coding: utf-8 -*-  код  hotelling.stats.hotelling_t2
# ref: https://dionresearch.github.io/hotelling/_modules/hotelling/stats.html#hotelling_diсt
"""Stats.py.

Hotelling's T-Squared multivariate test for one sample or two independent samples

See:
 Hotelling, Harold. (1931). The Generalization of Student's Ratio. Ann. Math. Statist. 2,
  no. 3, 360--378. doi:10.1214/aoms/1177732979.

https://projecteuclid.org/euclid.aoms/1177732979
"""
from warnings import warn

import numpy as np
from scipy.stats import f


def bessel_correction(x, y=None):
    """bessel_correction.

    Sampling tends to underestimate variability of a population. This is due to the fact that we are more likely to
    sample around the mean than near the extremities. Bessel's correction uses n−1 instead of n which is used to
    calculate variance etc, in order to correct for the bias in the estimation of the population variance.

    :param x: array-like, samples of observations
    :param y: array-like, samples of observations, optional
    :return: returns x_n - 1, y_n - 1
    """
    n1 = x.shape[0] - 1
    try:
        n1 = n1.compute()
    except AttributeError:
        pass
    if y is None:
        n2 = 0
    else:
        n2 = y.shape[0] - 1
        try:
            n2 = n2.compute()
        except AttributeError:
            pass
    return n1, n2



def inverse_covariance_matrix(x, y, bessel=True):
    """inverse_covariance_matrix.

    :param x: array-like, samples of observations
    :param y: array-like, samples of observations
    :param bessel: bool, apply bessel correction (default)
    :return: float, the pooled variance inverse, the pooled variance
    """
    _, *p = x.shape
    p = p[0] if p else 1
    s = pooled_covariance_matrix(x, y, bessel)
    try:
        ident_p = np.identity(p).compute
    except AttributeError:
        ident_p = np.identity(p)
    inv = np.linalg.solve(s, ident_p)
    return inv, s



def pooled_covariance_matrix(x, y, bessel=True):
    r"""pooled_covariance.

    Compute the pooled covariance matrix

    Equation:

    The pooled covariance matrix is defined as:

    .. math::
        S =  \\frac{n_xS_x + n_yS_y}{n_x+n_y}

    And with bessel correction as:

    .. math::
        S =  \\frac{(n_x-1)S_x + (n_y-1)S_y}{n_x+n_y-2}

    Reference
    ---------
    see: https://en.wikipedia.org/wiki/Hotelling%27s_T-squared_distribution#Pooled_covariance_matrix

    :param x: array-like, samples of observations
    :param y: array-like, samples of observations
    :param bessel: bool, apply bessel correction (default)
    :return: float, the pooled variance
    """
    if bessel:
        n1, n2 = bessel_correction(x, y)
    else:
        try:
            n1 = x.shape[0]
            n1 = n1.compute()
            n2 = y.shape[0]
            n2 = n2.compute()
        except AttributeError:
            n1 = x.shape[0]
            n2 = y.shape[0]
    try:
        s1 = n1 * x.cov().compute()

    except AttributeError:
        s1 = n1 * np.cov(x, rowvar=False)
    try:
        s2 = n2 * y.cov().compute()
    except AttributeError:
        s2 = n2 * np.cov(y, rowvar=False)
    s = (s1 + s2) / (n1 + n2)

    return s



def hotelling_t2(x, y=None, bessel=True, S=None):
    r"""hotelling_t2.

    Compute the Hotelling (T2) test statistic.

    It is the multivariate extension of the Student's t-test.
    Test the null hypothesis that two multivariate samples have the same underlying
    probability distribution, when specifying samples for x and y. The number of samples do not have
    to be the same, but the number of features does have to be equal.

    Equation:

    Hotelling's t-squared statistic is defined as:

    .. math::
        T^2 = n (\\bar{x} - {\mu})^{T} S^{-1} (\\bar{x} - {\mu})

    Where S is the pooled covariance matrix and ᵀ represents the transpose.

    The two sample t-squared statistic is defined as:

    .. math::
        T^2 = (\\bar{x} - \\bar{y})^{T} [S(\\frac1 n_x +\\frac 1 n_y)]^{-1} (\\bar{x}̄ - \\bar{y})

    References:
        - Hotelling, Harold. (1931). The Generalization of Student's Ratio. Ann. Math. Statist. 2, no. 3, 360--378.
          doi:10.1214/aoms/1177732979. https://projecteuclid.org/euclid.aoms/1177732979

        - Hotelling, Harold. (1955) Les Rapports entre les Methodes Statistiques recentes portant sur des Variables Multiples
          et l'Analyse Factorielle. 107-119.
          In: L'Analyse Factorielle et ses Applications. Centre National de la Recherche Scientifique, Paris.

        - Anderson T.W. (1992) Introduction to Hotelling (1931) The Generalization of Student’s Ratio.
          In: Kotz S., Johnson N.L. (eds) Breakthroughs in Statistics.
          Springer Series in Statistics (Perspectives in Statistics). Springer, New York, NY

    :param x: array-like, samples of observations for one or two sample test (required)
    :param y: for two sample test, array-like, samples of observations (optional), for one sample, list of means to test
    :param bessel: bool, apply bessel correction (default)
    :return:
        statistic: float,
            the t2 statistic
        f_value: float,
            the f value
        p_value: float,
            the p value
        s: 2d array,
            the pooled variance
    """  # noqa: W605
    try:
        nx, p = x.shape
    except AttributeError as ex:
        if "list" in str(ex):
            x = np.asarray(x)
            nx, *p = x.shape
            p = p[0] if p else 1
            y = np.asarray(y)
        else:
            warn("Error: The two samples must be in arrays or dataframes format.")
            raise ValueError

    # samples observed means
    try:
        nx = nx.compute()
        x_bar = x.mean(0).compute()
    except AttributeError:  # series has no attribute compute
        x_bar = x.mean(0)

    one_sample = False
    if y is None:
        # One sample T-squared
        one_sample = True
        y = np.zeros(p)
        ny = None
        py = p
        diff_bar = x_bar - y

    else:
        ny, *py = y.shape
        if len(py) == 0:
            one_sample = True
            py = p
            diff_bar = x_bar - y
        else:
            # Two sample T-squared
            py = py[0] if py else 1
            try:
                ny = ny.compute()
                y_bar = y.mean(0).compute()
            except AttributeError:  # series has no attribute compute
                y_bar = y.mean(0)
            # difference of means
            diff_bar = x_bar - y_bar
    if p != py:
        warn(
            f"Error: the two samples must have the same number of features ({p} != {py})."
        )
        raise ValueError

    # bessel correction ( -1 )
    if bessel:
        n1, n2 = bessel_correction(x, y)
    else:
        n1 = nx
        n2 = ny
    if one_sample:
        n = nx
    else:
        n = n1 + n2

    # calculate the T2 statistics
    # Technically, we use diff_bar.T for the transpose, but with Pandas, a 1 dimensional dataframe
    # is automatically aligned for @ and is not required
    if one_sample:
        if S is not None:
            cov = S
        else:
            try:
                cov = x.cov().compute()
            except AttributeError:
                try:
                    cov = x.cov()
                except AttributeError:
                    cov = np.cov(x, rowvar=False)
        inv_cov = np.linalg.pinv(cov)
        # for f test
        # term = (n - p) / (p * (n - 1))  # getting different results
        t2_stat = n * (diff_bar.T @ inv_cov @ diff_bar)
        if S is not None:
            return t2_stat
        # f statistic
        # TODO: use chi square instead of f statistic for large sample
        f_value = (n - p) * t2_stat / ((n - 1) * p)
    else:
        # pooled covariance
        inv_s, s = inverse_covariance_matrix(x, y, bessel)
        t2_stat = nx * ny / (nx + ny) * (diff_bar.T @ inv_s @ diff_bar)
        # f statistic
        # TODO: use chi square instead of f statistic for large sample
        f_value = (nx + ny - p - 1) * t2_stat / (n * p)

    # p-value
    p_value = f.sf(f_value, p, n - p)  # survival function, 1 - cdf

    # return the list of results
    return t2_stat, f_value, p_value, cov if one_sample else s


In [23]:
# Тест на рівність коваріацій у двох вибірках
#  Example 7.3.2  (Table 5.1)  Rencher
path = 'c:/Users/vica/Dropbox/KAU-Stat2/multivariate_analysis/T5_1_PSYCH.DAT'
Data_5_1 = np.loadtxt(path, dtype=int)
print(Data_5_1)

[[ 1 15 17 24 14]
 [ 1 17 15 32 26]
 [ 1 15 14 29 23]
 [ 1 13 12 10 16]
 [ 1 20 17 26 28]
 [ 1 15 21 26 21]
 [ 1 15 13 26 22]
 [ 1 13  5 22 22]
 [ 1 14  7 30 17]
 [ 1 17 15 30 27]
 [ 1 17 17 26 20]
 [ 1 17 20 28 24]
 [ 1 15 15 29 24]
 [ 1 18 19 32 28]
 [ 1 18 18 31 27]
 [ 1 15 14 26 21]
 [ 1 18 17 33 26]
 [ 1 10 14 19 17]
 [ 1 18 21 30 29]
 [ 1 18 21 34 26]
 [ 1 13 17 30 24]
 [ 1 16 16 16 16]
 [ 1 11 15 25 23]
 [ 1 16 13 26 16]
 [ 1 16 13 23 21]
 [ 1 18 18 34 24]
 [ 1 16 15 28 27]
 [ 1 15 16 29 24]
 [ 1 18 19 32 23]
 [ 1 18 16 33 23]
 [ 1 17 20 21 21]
 [ 1 19 19 30 28]
 [ 2 13 14 12 21]
 [ 2 14 12 14 26]
 [ 2 12 19 21 21]
 [ 2 12 13 10 16]
 [ 2 11 20 16 16]
 [ 2 12  9 14 18]
 [ 2 10 13 18 24]
 [ 2 10  8 13 23]
 [ 2 12 20 19 23]
 [ 2 11 10 11 27]
 [ 2 12 18 25 25]
 [ 2 14 18 13 26]
 [ 2 14 10 25 28]
 [ 2 13 16  8 14]
 [ 2 14  8 13 25]
 [ 2 13 16 23 28]
 [ 2 16 21 26 26]
 [ 2 14 17 14 14]
 [ 2 16 16 15 23]
 [ 2 13 16 23 24]
 [ 2  2  6 16 21]
 [ 2 14 16 22 26]
 [ 2 17 17 22 28]
 [ 2 16 13

In [24]:
# 1: М, 2: F. Розбиваємо на 2 таблиці, по 32 
len(Data_5_1)
Data_5_1M=Data_5_1[0:32,:]  #останній не входить, тут рядки з 0 по 31
Data_5_1M

array([[ 1, 15, 17, 24, 14],
       [ 1, 17, 15, 32, 26],
       [ 1, 15, 14, 29, 23],
       [ 1, 13, 12, 10, 16],
       [ 1, 20, 17, 26, 28],
       [ 1, 15, 21, 26, 21],
       [ 1, 15, 13, 26, 22],
       [ 1, 13,  5, 22, 22],
       [ 1, 14,  7, 30, 17],
       [ 1, 17, 15, 30, 27],
       [ 1, 17, 17, 26, 20],
       [ 1, 17, 20, 28, 24],
       [ 1, 15, 15, 29, 24],
       [ 1, 18, 19, 32, 28],
       [ 1, 18, 18, 31, 27],
       [ 1, 15, 14, 26, 21],
       [ 1, 18, 17, 33, 26],
       [ 1, 10, 14, 19, 17],
       [ 1, 18, 21, 30, 29],
       [ 1, 18, 21, 34, 26],
       [ 1, 13, 17, 30, 24],
       [ 1, 16, 16, 16, 16],
       [ 1, 11, 15, 25, 23],
       [ 1, 16, 13, 26, 16],
       [ 1, 16, 13, 23, 21],
       [ 1, 18, 18, 34, 24],
       [ 1, 16, 15, 28, 27],
       [ 1, 15, 16, 29, 24],
       [ 1, 18, 19, 32, 23],
       [ 1, 18, 16, 33, 23],
       [ 1, 17, 20, 21, 21],
       [ 1, 19, 19, 30, 28]])

In [25]:
Data_5_1M_new=Data_5_1M[:,1:]
Data_5_1M_new

array([[15, 17, 24, 14],
       [17, 15, 32, 26],
       [15, 14, 29, 23],
       [13, 12, 10, 16],
       [20, 17, 26, 28],
       [15, 21, 26, 21],
       [15, 13, 26, 22],
       [13,  5, 22, 22],
       [14,  7, 30, 17],
       [17, 15, 30, 27],
       [17, 17, 26, 20],
       [17, 20, 28, 24],
       [15, 15, 29, 24],
       [18, 19, 32, 28],
       [18, 18, 31, 27],
       [15, 14, 26, 21],
       [18, 17, 33, 26],
       [10, 14, 19, 17],
       [18, 21, 30, 29],
       [18, 21, 34, 26],
       [13, 17, 30, 24],
       [16, 16, 16, 16],
       [11, 15, 25, 23],
       [16, 13, 26, 16],
       [16, 13, 23, 21],
       [18, 18, 34, 24],
       [16, 15, 28, 27],
       [15, 16, 29, 24],
       [18, 19, 32, 23],
       [18, 16, 33, 23],
       [17, 20, 21, 21],
       [19, 19, 30, 28]])

In [26]:
n_M=len(Data_5_1M_new)
n_M

32

In [27]:
Data_5_1F=Data_5_1[32:,:]
Data_5_1F_new=Data_5_1F[:,1:]
n_F=len(Data_5_1F_new)
n_F

32

In [28]:
S_F= np.cov(Data_5_1M_new.T)
S_M= np.cov(Data_5_1F_new.T)
S= np.cov(Data_5_1[:,1:].T)
Spl= ((n_F-1)*S_F+ (n_M-1)*S_M)/(n_M+n_F-2)
Spl

array([[ 7.16431452,  6.04737903,  5.69304435,  4.70060484],
       [ 6.04737903, 15.89415323,  8.49243952,  5.85584677],
       [ 5.69304435,  8.49243952, 29.35635081, 13.98084677],
       [ 4.70060484,  5.85584677, 13.98084677, 22.32056452]])

In [30]:
Mean_M= np.mean(Data_5_1M_new,axis=0)
Mean_F= np.mean(Data_5_1F_new,axis=0)

In [31]:
T2_2samples=((n_F*n_M)/(n_F+n_M))*((Mean_M.T-Mean_F.T)@ np.linalg.inv(Spl) @ (Mean_M-Mean_F)) 
T2_2samples

97.60149652776889

In [32]:
# рахуємо F статистику
d=4
F=T2_2samples*(n_F+n_M-d-1)/((n_F+n_M-2)*d)
F

23.219710867493404

In [36]:
# Застосуємо вбудовану функцію (див. довументацію)
hotelling_t2(Data_5_1M_new, Data_5_1F_new, bessel=True, S=None)   
# Є момент:  при  bessel=False   статистика будується трохи не так!  f_value = (nx + ny - p - 1) * t2_stat / (n * p)
# Тут  n=nx+ny, а у нас в знаменнику n-2, а не  n 
# bessel=True - тоді так, як у нас
# Висновок--- ТРЕБА ЧИТАТИ ДОКУМЕНТАЦІЮ!!! 

(97.60149652776889,
 23.219710867493404,
 1.7161166043309273e-11,
 array([[ 7.16431452,  6.04737903,  5.69304435,  4.70060484],
        [ 6.04737903, 15.89415323,  8.49243952,  5.85584677],
        [ 5.69304435,  8.49243952, 29.35635081, 13.98084677],
        [ 4.70060484,  5.85584677, 13.98084677, 22.32056452]]))

In [39]:
# Ми припускали, що спостереження нормальні. Наведемо декілька тестів нормальності
# Тест Шапіро-Уілка. Це одновимірний тест, для тестування векторів потрібно інше! 
from scipy import stats
shapiro_test_M1 = stats.shapiro(Data_5_1M_new[:,1])  # 
shapiro_test_M1      

ShapiroResult(statistic=0.9140006899833679, pvalue=0.014341438189148903)

In [41]:
# Перевіримо тепер по координатам: 
for i in range(0,4):
    print([i])
    a,b=stats.shapiro(Data_5_1M_new[:,i])
    print(a,"Статистика", b, "p-value")   #  не дуже підходить...

[0]
0.9349082708358765 Статистика 0.05374595522880554 p-value
[1]
0.9140006899833679 Статистика 0.014341438189148903 p-value
[2]
0.8983452320098877 Статистика 0.005622181110084057 p-value
[3]
0.940362811088562 Статистика 0.07666302472352982 p-value


In [42]:
# Перевіримо тепер по координатам, тест Колмогорова-Смірнова: 
for i in range(0,4):
    print([i])
    a,b=stats.kstest(Data_5_1M_new[:,i], 'norm')
    print(a,"Статистика", b, "p-value")   #  не дуже підходить...

[0]
1.0 Статистика 0.0 p-value
[1]
0.9999997133484281 Статистика 8.637110608912666e-210 p-value
[2]
1.0 Статистика 0.0 p-value
[3]
1.0 Статистика 0.0 p-value


In [43]:
# pingouin багатовимірний тест на нормальність  (Henze, Zirkler (1990))
pg.multivariate_normality(Data_5_1M_new, alpha=.05)

HZResults(hz=23.483889208712167, pval=4.603551967742349e-125, normal=False)

In [46]:
# D’Agostino, Pearson  (1973)
from scipy import stats
stats.normaltest(Data_5_1M_new)

NormaltestResult(statistic=array([ 4.00341947, 10.06075195, 13.10544202,  2.02431211]), pvalue=array([0.13510409, 0.00653635, 0.00142623, 0.36343455]))