In [1]:
# Посилання: https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8

import numpy as np
# введемо вектори як 1D numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nскалярний добуток:", np.inner(a, b))   # скалярний добуток, \n перед словом означає новий рядок
print("dot:", np.dot(a, b))


скалярний добуток: 32
dot: 32


In [2]:
# Матриці як масиви
a = np.array([[1, 2], [3, 4]])  
b = np.array([[5, 6, 7], [8, 9, 10]])

# Мариці як матриці
c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print("\nc", type(c))  
print(c)
print("\nd", type(d))
print(d)
print("\nдобуток масивів")
print(np.dot(a, b))
print("\nдобуток матриць")
print(np.dot(c, d))


c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]

добуток масивів
[[21 24 27]
 [47 54 61]]

добуток матриць
[[21 24 27]
 [47 54 61]]


In [3]:
# Транспонування

a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

print("\nЗа допомоги np.transpose(a)")
print(np.transpose(a))

print("\nЗа допомоги ndarray.transpose()")
print(a.transpose())

print("\nЗа допомоги ndarray.T")
print(a.T)

[[1 2]
 [3 4]
 [5 6]]

За допомоги np.transpose(a)
[[1 3 5]
 [2 4 6]]

За допомоги ndarray.transpose()
[[1 3 5]
 [2 4 6]]

За допомоги ndarray.T
[[1 3 5]
 [2 4 6]]


In [4]:
# Слід матриці
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
print("\nСлід:", a.trace())  
print("Слід:", sum(a.diagonal()))  # сума на діагоналі не смінюється! 

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Слід: 7
Слід: 7


In [5]:
# Детермінант матриці
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
det = np.linalg.det(a)
print("\nдетермінант:", det)            # значення, я є
print("\nокруглений детермінант:", np.round(det))  # округлити 



детермінант: 4.999999999999999

округлений детермінант: 5.0


In [6]:
# Обернена матриця
inv = np.linalg.inv(a)
print("\nобернена матриця a = ")
print(inv)


обернена матриця a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


In [7]:
# Псевдо-обернена матриця, якщо детермінант =0. 
a = np.array([[2, 8],
               [1, 4]])
det = np.linalg.det(a)
print("\nдетермінант:", np.round(det))
pinv = np.linalg.pinv(a)
print("\nпсевдо-обернена матриця a = ")
print(pinv)


детермінант: 0.0

псевдо-обернена матриця a = 
[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


In [8]:
# Власні вектори і власні числа
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
w, v = np.linalg.eig(a)
print("\nвласні числа:")
print(w)
print("\nвласні вектори:")
print(v)


власні числа:
[5. 1. 1.]

власні вектори:
[[ 0.57735027  0.90453403  0.36601928]
 [ 0.57735027 -0.30151134 -0.55609927]
 [ 0.57735027 -0.30151134  0.74617926]]
